"""Tennis EOD report — daily performance summary appended to Obsidian vault.

Run by cron at 22:00 UTC. Reads state.json, trades.jsonl, skipped.jsonl
and pending_selections.jsonl, aggregates today's activity, and appends
(or replaces) an "EOD Performance" section to <vault>/YYYY-MM-DD.md.

CLI: python tennis_eod_report.py
"""

from __future__ import annotations

import json
import logging
import os
import sys
from datetime import datetime, timezone, date
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))
from tennis_dry_run import (  # noqa: E402
    STATE_DIR,
)

log = logging.getLogger("tennis_eod_report")


def _today_utc() -> date:
    return datetime.now(timezone.utc).date()


def _read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows: list[dict] = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except Exception:
                pass
    return rows


def _is_today(ts_iso: str, today: date) -> bool:
    if not ts_iso:
        return False
    try:
        return (
            datetime.fromisoformat(ts_iso).astimezone(timezone.utc).date() == today
        )
    except Exception:
        return False


def write_eod_report(
    now_utc: datetime,
    state_dir: Path,
    vault_dir: Path,
    rolling_path: Optional[Path] = None,
) -> Path:
    """Append/replace EOD section in today's daily file + re-render rolling file."""
    from tennis_kelly import replay_three_bankrolls
    from tennis_portfolio import (
        render_portfolio_block,
        render_open_picks_block,
        render_closed_trades_block,
        render_performance_block,
        render_backtest_comparison_block,
        render_today_placer_activity_block,
        render_today_settlements_block,
    )

    today = now_utc.date()
    today_iso = today.isoformat()

    state_file = Path(state_dir) / "state.json"
    trades_file = Path(state_dir) / "trades.jsonl"
    skipped_file = Path(state_dir) / "skipped.jsonl"

    state: dict = {}
    if state_file.exists():
        try:
            state = json.loads(state_file.read_text(encoding="utf-8"))
        except Exception:
            state = {}

    all_trades = _read_jsonl(trades_file)
    skipped_today = [
        s for s in _read_jsonl(skipped_file)
        if _is_today(s.get("ts", ""), today)
    ]

    placed = [t for t in all_trades if t.get("type") == "open"]
    settled = [t for t in all_trades if t.get("type") == "settled"]
    placed_today = [p for p in placed if _is_today(p.get("ts", ""), today)]
    settled_today = [s for s in settled if _is_today(s.get("ts", ""), today)]
    placed_lookup = {p["pick_id"]: p for p in placed}
    placer_skips_today = [s for s in skipped_today if s.get("source") == "placer"]

    replay = replay_three_bankrolls(settled, placed, starting_balance=500.0,
                                    today=today)

    # Build EOD section
    eod_section = "\n".join([
        "",
        f"## EOD Performance — {today_iso}",
        "",
        f"EOD run timestamp: {now_utc.replace(microsecond=0).isoformat()}",
        "",
        render_portfolio_block(replay, now_utc),
        render_today_placer_activity_block(placed_today, placer_skips_today, replay),
        render_today_settlements_block(settled_today, placed_lookup),
        "---",
        f"_Generated by `tennis_eod_report.py` at "
        f"{now_utc.strftime('%H:%M')} UTC._",
        "",
    ])

    # Append/replace EOD section in daily file
    report_path = Path(vault_dir) / f"{today_iso}.md"
    if not report_path.exists():
        stub = (
            f"---\n"
            f"date: {today_iso}\n"
            f"type: tennis-daily-report\n"
            f"tags: [tennis, dry-run]\n"
            f"---\n\n"
            f"# Tennis Daily Report — {today_iso}\n\n"
            f"_No morning identifier report was generated for this date._\n"
        )
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(stub, encoding="utf-8")

    body = report_path.read_text(encoding="utf-8")
    eod_marker = f"## EOD Performance — {today_iso}"
    if eod_marker in body:
        idx = body.index(eod_marker)
        line_start = body.rfind("\n", 0, idx) + 1
        body = body[:line_start].rstrip() + "\n"
    body = body.rstrip() + "\n" + eod_section
    report_path.write_text(body, encoding="utf-8")

    # Re-render rolling file
    if rolling_path is not None:
        open_picks = state.get("open_picks", {}) or {}
        rolling_lines = [
            "---",
            "tags: [tennis, dry-run, report]",
            "type: report",
            "---",
            "",
            f"## Tennis Dry Run Report — {now_utc.strftime('%Y-%m-%d %H:%M')} UTC",
            "",
            render_portfolio_block(replay, now_utc),
            render_open_picks_block(open_picks, replay),
            render_closed_trades_block(settled, placed, n=30),
            render_performance_block(replay),
            render_backtest_comparison_block(replay),
            "---",
            f"_Generated by `tennis_eod_report.py` at "
            f"{now_utc.strftime('%H:%M')} UTC._",
            "",
        ]
        rolling_path = Path(rolling_path)
        rolling_path.parent.mkdir(parents=True, exist_ok=True)
        rolling_path.write_text("\n".join(rolling_lines), encoding="utf-8")

    return report_path


def main(argv=None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    )

    now_utc = datetime.now(timezone.utc)

    state_dir = STATE_DIR
    vault_dir = Path(os.getenv(
        "OBSIDIAN_VAULT_DIR",
        "/opt/vps-hub/vault/finance-brain/10-Projects/Tennis-Automated/Daily-Reports",
    ))
    rolling_path_env = os.getenv(
        "TENNIS_ROLLING_REPORT",
        "/opt/vps-hub/vault/finance-brain/10-Projects/Tennis-Automated/Tennis-Dry-Run-Report.md",
    )
    rolling_path = Path(rolling_path_env) if rolling_path_env else None

    try:
        report_path = write_eod_report(
            now_utc=now_utc,
            state_dir=state_dir,
            vault_dir=vault_dir,
            rolling_path=rolling_path,
        )
        log.info("EOD report written: %s", report_path)
        if rolling_path:
            log.info("Rolling report refreshed: %s", rolling_path)
    except Exception as exc:
        log.exception("EOD vault write failed: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
